import type { NanoBananaGalleryItem, TemplateCatalogEntry, VeoShowcaseItem } from "./types";

export const templateCatalog: TemplateCatalogEntry[] = [
  {
    id: "velox-showroom",
    name: "Velox Showroom",
    category: "Portfolio",
    description:
      "Cinematic automotive gallery with Three.js scroll choreography, gold accents, and immersive product storytelling.",
    featured: true,
    badge: "Featured",
    htmlPath: "/template-demos/velox-showroom.html",
    previewImage: "/templates/previews/velox-showroom.jpg",
    mobilePreviewImage: "/templates/previews/velox-showroom-mobile.jpg",
    bgColor: "#080808",
    pages: 8,
    components: 42,
    uses: 2840,
    updatedAt: "2026-06-13",
  },
  {
    id: "nexus",
    name: "Nexus",
    category: "SaaS",
    description:
      "Cosmic-scale intelligence landing page with WebGL nebula scenes, chrome typography, and scroll-driven narrative.",
    featured: true,
    badge: "Featured",
    htmlPath: "/template-demos/nexus.html",
    previewImage: "/templates/previews/nexus.jpg",
    mobilePreviewImage: "/templates/previews/nexus-mobile.jpg",
    bgColor: "#010208",
    pages: 7,
    components: 38,
    uses: 3120,
    updatedAt: "2026-06-13",
  },
  {
    id: "stone-archive",
    name: "Stone Archive",
    category: "Portfolio",
    description:
      "Immersive 3D portfolio archive with scroll-reactive identity panels, forge sections, and cinematic HUD typography.",
    featured: true,
    badge: "Featured",
    htmlPath: "/template-demos/stone-archive.html",
    previewImage: "/templates/previews/stone-archive.jpg",
    mobilePreviewImage: "/templates/previews/stone-archive-mobile.jpg",
    bgColor: "#000000",
    pages: 6,
    components: 36,
    uses: 2650,
    updatedAt: "2026-06-15",
  },
  {
    id: "chen-lei",
    name: "Chen Lei",
    category: "Agency",
    description:
      "Creative technologist portfolio with WebGL ground plane, monospace editorial type, and precision motion design.",
    featured: true,
    htmlPath: "/template-demos/chen-lei.html",
    previewImage: "/templates/previews/chen-lei.jpg",
    mobilePreviewImage: "/templates/previews/chen-lei-mobile.jpg",
    bgColor: "#000000",
    pages: 6,
    components: 34,
    uses: 1980,
    updatedAt: "2026-06-13",
  },
  {
    id: "noir-restaurant",
    name: "NOIR",
    category: "Ecommerce",
    description:
      "Fine dining experience with gold-shimmer loading, editorial serif typography, and atmospheric reservation flow.",
    featured: false,
    htmlPath: "/template-demos/noir-restaurant.html",
    previewImage: "/templates/previews/noir-restaurant.jpg",
    mobilePreviewImage: "/templates/previews/noir-restaurant-mobile.jpg",
    bgColor: "#0A0804",
    pages: 7,
    components: 40,
    uses: 2240,
    updatedAt: "2026-06-13",
  },
  {
    id: "chronos-infinitum",
    name: "ÆTHER",
    category: "Design",
    description:
      "Architects of time — cosmic canvas chapters, gold celestial cursor, and poetic scroll-driven storytelling.",
    featured: false,
    htmlPath: "/template-demos/chronos-infinitum.html",
    previewImage: "/templates/previews/chronos-infinitum.jpg",
    mobilePreviewImage: "/templates/previews/chronos-infinitum-mobile.jpg",
    bgColor: "#02020A",
    pages: 6,
    components: 32,
    uses: 1760,
    updatedAt: "2026-06-13",
  },
  {
    id: "sketchbook-3d",
    name: "Inside My Mind",
    category: "Creator",
    description:
      "Interactive 3D sketchbook world with hand-drawn typography, playful HUD overlays, and exploratory navigation.",
    featured: false,
    htmlPath: "/template-demos/sketchbook-3d.html",
    previewImage: "/templates/previews/sketchbook-3d.jpg",
    mobilePreviewImage: "/templates/previews/sketchbook-3d-mobile.jpg",
    bgColor: "#f5f0e8",
    pages: 5,
    components: 28,
    uses: 1540,
    updatedAt: "2026-06-13",
  },
  {
    id: "the-last-library",
    name: "The Last Library",
    category: "Creator",
    description:
      "Literary universe with starfield canvas, floating book spines, and screen-based narrative exploration.",
    featured: false,
    htmlPath: "/template-demos/the-last-library.html",
    previewImage: "/templates/previews/the-last-library.jpg",
    mobilePreviewImage: "/templates/previews/the-last-library-mobile.jpg",
    bgColor: "#06040f",
    pages: 6,
    components: 30,
    uses: 1420,
    updatedAt: "2026-06-14",
  },
];

export const nanoBananaGallery: NanoBananaGalleryItem[] = [
  {
    id: "product-lifestyle",
    src: "/gallery/nano-banana/product-lifestyle.png",
    alt: "Premium monochrome product lifestyle render with watch, perfume, and headphones",
    prompt: "Luxury product flat lay, dark studio lighting, enterprise SaaS campaign visual",
  },
  {
    id: "holographic-workspace",
    src: "/gallery/nano-banana/holographic-workspace.png",
    alt: "Futuristic holographic workspace with floating UI panels and blue neon accents",
    prompt: "Holographic creative workspace, glass UI panels, cyber blue accent lighting",
  },
  {
    id: "glass-dashboard",
    src: "/gallery/nano-banana/glass-dashboard.png",
    alt: "Glassmorphism analytics dashboard floating in a deep blue nebula",
    prompt: "Glass dashboard UI, data visualization, deep space gradient background",
  },
  {
    id: "stoneai-showroom",
    src: "/gallery/nano-banana/stoneai-showroom.png",
    alt: "StoneAI branded showroom wall with smartwatch product grid",
    prompt: "StoneAI product showroom, premium watch grid, collaborative presentation scene",
  },
];

/** Ready for real Veo assets — set videoSrc and posterSrc when files are available. */
export const veoShowcaseItems: VeoShowcaseItem[] = [
  {
    id: "hero-loop",
    title: "Hero loop",
    description: "Atmospheric homepage background with slow camera drift and product focus.",
    placeholder: true,
    posterSrc: "/gallery/veo/hero-loop-poster.jpg",
  },
  {
    id: "product-demo",
    title: "Product demo",
    description: "Short feature walkthrough clip generated from a single prompt and brand brief.",
    placeholder: true,
    posterSrc: "/gallery/veo/product-demo-poster.jpg",
  },
  {
    id: "launch-film",
    title: "Launch film",
    description: "Cinematic launch sequence for campaigns, landing pages, and social cutdowns.",
    placeholder: true,
    posterSrc: "/gallery/veo/launch-film-poster.jpg",
  },
];
