import type { TemplateSeoPage } from "@/lib/blog/types";
import { h2, p, ul, ctaTop, ctaMiddle, ctaBottom, link } from "../blocks";

export const portfolioTemplate: TemplateSeoPage = {
  slug: "portfolio",
  name: "Portfolio",
  seoTitle: "Portfolio Website Template — AI-Generated by StoneAI",
  metaDescription:
    "Build a creative portfolio with StoneAI. Project showcases, case studies, and cinematic 3D design—personalized from your prompt.",
  title: "Portfolio Website Template",
  subtitle: "Frame your work with design that competes on taste",
  previewGradient: "linear-gradient(135deg, #0d0d0d 0%, #1f1f2e 50%, #2a1f3d 100%)",
  features: [
    { title: "Project grid", description: "Curated work display with hover states and categories." },
    { title: "Case study depth", description: "Challenge, process, and outcome for key projects." },
    { title: "Personal brand", description: "About section with positioning and contact paths." },
    { title: "Cinematic option", description: "3D heroes for designers and motion professionals." },
  ],
  useCases: ["UX/UI designers", "Photographers", "Developers", "Consultants", "Art directors"],
  faq: [
    { question: "How many projects can I show?", answer: "Unlimited—add projects in the visual editor." },
    { question: "Good for developers?", answer: "Yes. Include tech stack, links, and outcome metrics." },
    { question: "Can I use a custom domain?", answer: "Connect your domain after publishing." },
    { question: "Different from Behance?", answer: "Owned SEO, full design control, and direct client contact." },
  ],
  relatedArticleSlugs: ["best-portfolio-website-builders", "how-to-create-interactive-3d-websites"],
  content: [
    ctaTop(),
    h2("portfolio-template", "Portfolio that converts browsers into clients"),
    p("This template balances visual impact with clarity—prospects understand what you do and how to hire you within seconds."),
    ul(["Positioning hero", "Work grid", "Featured case studies", "Skills", "About", "Contact"]),
    ctaMiddle(),
    link("best-portfolio-website-builders", "Best portfolio website builders"),
    ctaBottom(),
  ],
};
