import type { TemplateSeoPage } from "@/lib/blog/types";
import { h2, h3, p, ul, ctaTop, ctaMiddle, ctaBottom, link } from "../blocks";

export const realEstateTemplate: TemplateSeoPage = {
  slug: "real-estate",
  name: "Real Estate",
  seoTitle: "Real Estate Website Template — AI-Generated by StoneAI",
  metaDescription:
    "Launch a premium real estate website with StoneAI's AI template. Property showcases, agent bios, lead capture, and cinematic design—customized from your prompt.",
  title: "Real Estate Website Template",
  subtitle: "Turn listings into leads with a site that matches your market",
  previewGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)",
  features: [
    { title: "Listing galleries", description: "Showcase properties with image-forward layouts and feature highlights." },
    { title: "Agent authority", description: "Bio, credentials, and testimonials that build trust pre-call." },
    { title: "Lead capture", description: "Strategic inquiry forms on high-intent pages." },
    { title: "Neighborhood pages", description: "SEO-ready area guides that attract local search traffic." },
  ],
  useCases: ["Individual agents", "Luxury brokers", "Boutique brokerages", "Property developers"],
  faq: [
    { question: "Can I customize the real estate template?", answer: "Yes. Generate from a prompt, then edit every section visually in StoneAI." },
    { question: "Does it work for commercial real estate?", answer: "Absolutely. Describe your commercial focus in the prompt for tailored sections." },
    { question: "Can I add my listings?", answer: "Add property images, descriptions, and details in gallery and listing sections." },
    { question: "Is mobile included?", answer: "All StoneAI sites are responsive by default." },
  ],
  relatedArticleSlugs: ["ai-website-builder-real-estate", "best-3d-website-builders"],
  content: [
    ctaTop(),
    h2("template-overview", "Real estate template overview"),
    p("StoneAI's real estate template combines cinematic heroes, property galleries, and conversion-focused contact flows. Unlike static templates, every generation adapts to your market, brand, and specialty."),
    h2("sections-included", "Sections included"),
    ul(["Cinematic hero with market positioning", "Featured listings grid", "About the agent/brokerage", "Client testimonials", "Neighborhood highlights", "Contact and valuation CTA"]),
    ctaMiddle(),
    h2("generate-yours", "Generate your real estate site"),
    p("Click Generate, describe your market and brand, and refine in the visual editor. Publish on your domain the same day."),
    link("ai-website-builder-real-estate", "AI website builder for real estate guide"),
    ctaBottom(),
  ],
};
